<a href="https://colab.research.google.com/github/AIML2435/2435_STAT-MLasssignments/blob/main/ProjectSTML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [84]:
df = pd.read_csv('/content/google_review_ratings.csv')
print (df)

           User  Category 1  Category 2  Category 3  Category 4  Category 5  \
0        User 1        0.00        0.00        3.63        3.65        5.00   
1        User 2        0.00        0.00        3.63        3.65        5.00   
2        User 3        0.00        0.00        3.63        3.63        5.00   
3        User 4        0.00        0.50        3.63        3.63        5.00   
4        User 5        0.00        0.00        3.63        3.63        5.00   
...         ...         ...         ...         ...         ...         ...   
5451  User 5452        0.91        5.00        4.00        2.79        2.77   
5452  User 5453        0.93        5.00        4.02        2.79        2.78   
5453  User 5454        0.94        5.00        4.03        2.80        2.78   
5454  User 5455        0.95        4.05        4.05        2.81        2.79   
5455  User 5456        0.95        4.07        5.00        2.82        2.80   

      Category 6  Category 7  Category 8  Category 

In [85]:
print("Missing values:", df.isnull().sum())

Missing values: User              0
Category 1        0
Category 2        0
Category 3        0
Category 4        0
Category 5        0
Category 6        0
Category 7        0
Category 8        0
Category 9        0
Category 10       0
Category 11       0
Category 12       1
Category 13       0
Category 14       0
Category 15       0
Category 16       0
Category 17       0
Category 18       0
Category 19       0
Category 20       0
Category 21       0
Category 22       0
Category 23       0
Category 24       1
Unnamed: 25    5454
dtype: int64


In [86]:
print(df.columns)

Index(['User', 'Category 1', 'Category 2', 'Category 3', 'Category 4',
       'Category 5', 'Category 6', 'Category 7', 'Category 8', 'Category 9',
       'Category 10', 'Category 11', 'Category 12', 'Category 13',
       'Category 14', 'Category 15', 'Category 16', 'Category 17',
       'Category 18', 'Category 19', 'Category 20', 'Category 21',
       'Category 22', 'Category 23', 'Category 24', 'Unnamed: 25'],
      dtype='object')


In [39]:
X = df['Category 1']
y = df['Category 2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

1115    1.40
1041    0.92
1647    1.45
3316    2.59
4716    1.30
        ... 
3772    0.79
5191    1.42
5226    0.53
5390    2.60
860     3.64
Name: Category 1, Length: 4364, dtype: float64
5149    1.38
3196    1.17
2406    1.02
4588    1.31
3184    0.99
        ... 
1862    1.30
2742    2.42
4663    0.73
4362    1.02
757     1.67
Name: Category 1, Length: 1092, dtype: float64
1115    1.39
1041    1.49
1647    1.45
3316    2.74
4716    1.33
        ... 
3772    5.00
5191    1.41
5226    0.52
5390    2.61
860     5.00
Name: Category 2, Length: 4364, dtype: float64
5149    1.41
3196    1.20
2406    5.00
4588    1.33
3184    1.05
        ... 
1862    5.00
2742    2.58
4663    5.00
4362    1.05
757     2.62
Name: Category 2, Length: 1092, dtype: float64


In [50]:
print(df.dtypes)
print(df)

User            object
Category 1     float64
Category 2     float64
Category 3     float64
Category 4     float64
Category 5     float64
Category 6     float64
Category 7     float64
Category 8     float64
Category 9     float64
Category 10    float64
Category 11     object
Category 12    float64
Category 13    float64
Category 14    float64
Category 15    float64
Category 16    float64
Category 17    float64
Category 18    float64
Category 19    float64
Category 20    float64
Category 21    float64
Category 22    float64
Category 23    float64
Category 24    float64
Unnamed: 25    float64
dtype: object
           User  Category 1  Category 2  Category 3  Category 4  Category 5  \
0        User 1        0.00        0.00        3.63        3.65        5.00   
1        User 2        0.00        0.00        3.63        3.65        5.00   
2        User 3        0.00        0.00        3.63        3.63        5.00   
3        User 4        0.00        0.50        3.63        3.63        5

In [78]:
### Logistic Regression
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=10000)

In [75]:
### Logistic Regression
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train_tfidf, y_train)
y_pred_lr = lr.predict(X_test_tfidf)
print("Logistic Regression:")

Logistic Regression:


In [69]:
print("Accuracy:", accuracy_score(y_test, y_pred_lr))

Accuracy: 0.4551282051282051


In [70]:
print("Classification Report:")
print(classification_report(y_test, y_pred_lr))

Classification Report:
              precision    recall  f1-score   support

           0       0.31      0.25      0.28       131
           1       0.52      0.72      0.61       435
           2       0.41      0.40      0.41       305
           3       0.00      0.00      0.00        25
           4       0.00      0.00      0.00        23
           5       0.31      0.16      0.21       173

    accuracy                           0.46      1092
   macro avg       0.26      0.26      0.25      1092
weighted avg       0.41      0.46      0.42      1092



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [71]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

Confusion Matrix:
[[ 33  68  20   0   0  10]
 [ 29 315  79   0   0  12]
 [ 26 123 121   0   0  35]
 [  1   7  13   0   0   4]
 [  1  20   1   0   0   1]
 [ 16  71  58   0   0  28]]


In [73]:
### Support Vector Machine
svm = SVC()
svm.fit(X_train_tfidf, y_train)

SVC()

In [76]:
y_pred_svm = svm.predict(X_test_tfidf)
print("\nSupport Vector Machine:")


Support Vector Machine:


In [79]:
print("Accuracy:", accuracy_score(y_test, y_pred_svm))

Accuracy: 0.4551282051282051


In [80]:
print("Classification Report:")
print(classification_report(y_test, y_pred_svm))

Classification Report:
              precision    recall  f1-score   support

           0       0.31      0.25      0.28       131
           1       0.52      0.72      0.61       435
           2       0.41      0.40      0.41       305
           3       0.00      0.00      0.00        25
           4       0.00      0.00      0.00        23
           5       0.31      0.16      0.21       173

    accuracy                           0.46      1092
   macro avg       0.26      0.26      0.25      1092
weighted avg       0.41      0.46      0.42      1092



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [81]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Confusion Matrix:
[[ 33  68  20   0   0  10]
 [ 29 315  79   0   0  12]
 [ 26 123 121   0   0  35]
 [  1   7  13   0   0   4]
 [  1  20   1   0   0   1]
 [ 16  71  58   0   0  28]]
